"""
Django settings for formsbackend project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CORS_ALLOW_ALL_ORIGINS = True



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0dr^e9t!*$ghr0*!r=og(k#=l9&05jc-*!bs%1p+o+&2vmjy_5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'i9_form',
    'w4_form',
    'anti_harassment',
    'application_for_employment',
    'cell_phone_policy',
    'direct_deposit',
    'employee_emergency_contacts',
    'employee_payroll_information',
    'hippa_agreement',
    'receipt_of_company_property',
    'credential_comprehensive',
    'rest_framework',
'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'formsbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'formsbackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
i9_dir = os.path.join(MEDIA_ROOT, 'i9')
w4_dir = os.path.join(MEDIA_ROOT, 'w4')
anti_harassment = os.path.join(MEDIA_ROOT, 'anti_harassment')
application_for_employment = os.path.join(MEDIA_ROOT, 'application_for_employment')
cell_phone_policy = os.path.join(MEDIA_ROOT, 'cell_phone_policy')
direct_deposit = os.path.join(MEDIA_ROOT, 'direct_deposit')
employee_payroll_information = os.path.join(MEDIA_ROOT, 'employee_payroll_information')
emergency_contacts = os.path.join(MEDIA_ROOT, 'emergency_contacts')
hippa_agreement = os.path.join(MEDIA_ROOT, 'hippa_agreement')
credential_comprehensive = os.path.join(MEDIA_ROOT, 'credential_comprehensive')
if not os.path.exists(i9_dir):
    os.makedirs(i9_dir)
if not os.path.exists(w4_dir):
    os.makedirs(w4_dir)
if not os.path.exists(anti_harassment):
    os.makedirs(anti_harassment)
if not os.path.exists(application_for_employment):
    os.makedirs(application_for_employment)
if not os.path.exists(cell_phone_policy):
    os.makedirs(cell_phone_policy)
if not os.path.exists(direct_deposit):
    os.makedirs(direct_deposit)
if not os.path.exists(emergency_contacts):
    os.makedirs(emergency_contacts)
if not os.path.exists(employee_payroll_information):
    os.makedirs(employee_payroll_information)
if not os.path.exists(hippa_agreement):
    os.makedirs(hippa_agreement)
if not os.path.exists(credential_comprehensive):
    os.makedirs(credential_comprehensive)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
