# Generated by Django 5.0.6 on 2024-05-12 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anti_harassment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="antiharassmentrecord",
            name="policy_text",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="antiharassmentrecord",
            name="pdf_file",
            field=models.FileField(upload_to="anti_harassment/"),
        ),
    ]
