# Generated by Django 5.0.6 on 2024-05-12 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anti_harassment", "0002_antiharassmentrecord_policy_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="antiharassmentrecord",
            name="date_of_birth",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
