# Generated by Django 5.0.6 on 2024-05-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CredentialApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caqh_id", models.CharField(max_length=100)),
                ("caqh_login", models.CharField(max_length=100)),
                ("caqh_password", models.CharField(max_length=100)),
                ("npi_registration", models.CharField(max_length=100)),
                ("npi_number", models.CharField(max_length=100)),
                ("npi_password", models.CharField(max_length=100)),
                ("full_name", models.CharField(max_length=255)),
                ("ssn", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                ("place_of_birth", models.CharField(max_length=255)),
                ("home_address", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("specialty", models.CharField(max_length=255)),
                ("taxonomy", models.CharField(max_length=255)),
                ("fl_license_number", models.CharField(max_length=100)),
                ("document_type", models.CharField(max_length=100)),
                ("document", models.FileField(upload_to="documents/")),
                ("reason_if_no_document", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
