# Generated by Django 5.0.6 on 2024-05-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("i9_form", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpdf",
            name="pdf_file",
            field=models.FileField(upload_to="i9/"),
        ),
    ]
