# Generated by Django 5.0.6 on 2024-05-12 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "application_for_employment",
            "0002_alter_employmentapplication_pdf_file_qualification_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=15)),
                ("relationship", models.CharField(max_length=100)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="application_for_employment.employmentapplication",
                    ),
                ),
            ],
        ),
    ]
