# Generated by Django 5.0.6 on 2024-05-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=50)),
                ("address", models.TextField()),
                ("city_state_zip", models.CharField(max_length=100)),
                ("primary_contact_name", models.CharField(max_length=255)),
                ("primary_contact_relationship", models.CharField(max_length=100)),
                ("primary_contact_phone", models.CharField(max_length=50)),
                (
                    "primary_contact_alt_phone",
                    models.CharField(blank=True, max_length=50),
                ),
                ("secondary_contact_name", models.CharField(max_length=255)),
                ("secondary_contact_relationship", models.CharField(max_length=100)),
                ("secondary_contact_phone", models.CharField(max_length=50)),
                (
                    "secondary_contact_alt_phone",
                    models.CharField(blank=True, max_length=50),
                ),
                ("doctor_name", models.CharField(max_length=255)),
                ("doctor_phone", models.CharField(max_length=50)),
                ("doctor_address", models.TextField()),
                ("date_signed", models.DateField()),
                ("pdf_file", models.FileField(upload_to="emergency_contacts/")),
                ("signature_image", models.ImageField(upload_to="signatures/")),
            ],
        ),
    ]
