# Generated by Django 5.0.6 on 2024-05-13 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hippa_agreement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hipaaagreement",
            name="agreement_date",
        ),
        migrations.AddField(
            model_name="hipaaagreement",
            name="agreement_Month",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hipaaagreement",
            name="agreement_Year",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hipaaagreement",
            name="pdf_file",
            field=models.FileField(upload_to="hippa_agreement/"),
        ),
        migrations.AddField(
            model_name="hipaaagreement",
            name="agreement_Date",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
