# Generated by Django 5.0.6 on 2024-05-13 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hippa_agreement", "0002_remove_hipaaagreement_agreement_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hipaaagreement",
            old_name="agreement_Date",
            new_name="agreement_date",
        ),
        migrations.RenameField(
            model_name="hipaaagreement",
            old_name="agreement_Month",
            new_name="agreement_month",
        ),
        migrations.RenameField(
            model_name="hipaaagreement",
            old_name="agreement_Year",
            new_name="agreement_year",
        ),
    ]
