# Generated by Django 5.0.6 on 2024-05-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeePayroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_name", models.CharField(max_length=255)),
                ("date_of_hire", models.DateField()),
                ("original_position", models.CharField(max_length=255)),
                ("change_position_date", models.DateField(blank=True, null=True)),
                ("pay_type", models.CharField(max_length=50)),
                ("pay_frequency", models.CharField(max_length=50)),
                ("hire_pay_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("signature_image", models.ImageField(upload_to="signatures/")),
                ("date_signed", models.DateField()),
                ("pdf_file", models.FileField(upload_to="employee_payroll/")),
            ],
        ),
    ]
