# Generated by Django 5.0.6 on 2024-05-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_payroll_information", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeepayroll",
            name="pdf_file",
            field=models.FileField(upload_to="employee_payroll_information/"),
        ),
    ]
